# Generated by Django 5.0.7 on 2024-07-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
    ]
