# Generated by Django 5.0.7 on 2024-07-25 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0002_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
